# Generated by Django 5.0.6 on 2024-05-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='Menu',
            name='Estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.restaurante'),
        ),
    ]
